// Generated by gencpp from file ser_and_cli/numberResponse.msg
// DO NOT EDIT!


#ifndef SER_AND_CLI_MESSAGE_NUMBERRESPONSE_H
#define SER_AND_CLI_MESSAGE_NUMBERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ser_and_cli
{
template <class ContainerAllocator>
struct numberResponse_
{
  typedef numberResponse_<ContainerAllocator> Type;

  numberResponse_()
    : sum(0)  {
    }
  numberResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::ser_and_cli::numberResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ser_and_cli::numberResponse_<ContainerAllocator> const> ConstPtr;

}; // struct numberResponse_

typedef ::ser_and_cli::numberResponse_<std::allocator<void> > numberResponse;

typedef boost::shared_ptr< ::ser_and_cli::numberResponse > numberResponsePtr;
typedef boost::shared_ptr< ::ser_and_cli::numberResponse const> numberResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ser_and_cli::numberResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ser_and_cli::numberResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ser_and_cli::numberResponse_<ContainerAllocator1> & lhs, const ::ser_and_cli::numberResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ser_and_cli::numberResponse_<ContainerAllocator1> & lhs, const ::ser_and_cli::numberResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ser_and_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ser_and_cli::numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser_and_cli::numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser_and_cli::numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser_and_cli::numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_and_cli::numberResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser_and_cli::numberResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ser_and_cli::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::ser_and_cli::numberResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::ser_and_cli::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ser_and_cli/numberResponse";
  }

  static const char* value(const ::ser_and_cli::numberResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ser_and_cli::numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::ser_and_cli::numberResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ser_and_cli::numberResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numberResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ser_and_cli::numberResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ser_and_cli::numberResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SER_AND_CLI_MESSAGE_NUMBERRESPONSE_H
