// Generated by gencpp from file ser_and_cli/number.msg
// DO NOT EDIT!


#ifndef SER_AND_CLI_MESSAGE_NUMBER_H
#define SER_AND_CLI_MESSAGE_NUMBER_H

#include <ros/service_traits.h>


#include <ser_and_cli/numberRequest.h>
#include <ser_and_cli/numberResponse.h>


namespace ser_and_cli
{

struct number
{

typedef numberRequest Request;
typedef numberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct number
} // namespace ser_and_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ser_and_cli::number > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::ser_and_cli::number&) { return value(); }
};

template<>
struct DataType< ::ser_and_cli::number > {
  static const char* value()
  {
    return "ser_and_cli/number";
  }

  static const char* value(const ::ser_and_cli::number&) { return value(); }
};


// service_traits::MD5Sum< ::ser_and_cli::numberRequest> should match
// service_traits::MD5Sum< ::ser_and_cli::number >
template<>
struct MD5Sum< ::ser_and_cli::numberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ser_and_cli::number >::value();
  }
  static const char* value(const ::ser_and_cli::numberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser_and_cli::numberRequest> should match
// service_traits::DataType< ::ser_and_cli::number >
template<>
struct DataType< ::ser_and_cli::numberRequest>
{
  static const char* value()
  {
    return DataType< ::ser_and_cli::number >::value();
  }
  static const char* value(const ::ser_and_cli::numberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ser_and_cli::numberResponse> should match
// service_traits::MD5Sum< ::ser_and_cli::number >
template<>
struct MD5Sum< ::ser_and_cli::numberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ser_and_cli::number >::value();
  }
  static const char* value(const ::ser_and_cli::numberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser_and_cli::numberResponse> should match
// service_traits::DataType< ::ser_and_cli::number >
template<>
struct DataType< ::ser_and_cli::numberResponse>
{
  static const char* value()
  {
    return DataType< ::ser_and_cli::number >::value();
  }
  static const char* value(const ::ser_and_cli::numberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SER_AND_CLI_MESSAGE_NUMBER_H
